import { useEffect } from "react";
import Head from "next/head";
import SearchExercise from "../components/SearchExercise";
import { auth } from "../firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";

const Home = () => {
	const [user] = useAuthState(auth);
	const router = useRouter();

	useEffect(() => {
		if (!user) {
			router.push("/login");
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [user]);

	const name = user?.email.split("@").shift();

	const homePage = (
		<div>
			<Head>
				<title>Workout App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="../images/weightlifting-icon.svg" />
			</Head>
			{user && (
				<h2
					style={{
						display: "flex",
						alignItems: "center",
						justifyContent: "center",
					}}
				>
					Welcome {name}! What are you working out today?
				</h2>
			)}
			<SearchExercise />
		</div>
	);

	return homePage;
};

export default Home;
